#!/bin/bash

# Configuration
BASE_FILE="deployment/00_base.yml"
NETWORK_FILE="deployment/99_base.yml"
TARGET_FILE="docker-compose.yml"
ENV_FILE=".env"
DEPLOY_DIR="deployment"
ACTIVE_FILE=".active_services"

echo "============================================="
echo "   Docker Compose Builder Tool"
echo "============================================="
echo ""

# List of available services
SERVICES=(
    "nginx-proxy"
    "portainer"
    "adminer"
    "mysql"
    "postgres"
    "redis"
    "iot"
    "minio"
    "gotenberg"
)

# Load existing active services
ACTIVE_SERVICES=()
if [ -f "$ACTIVE_FILE" ]; then
    readarray -t ACTIVE_SERVICES < "$ACTIVE_FILE"
fi

echo "Select services to TOGGLE (Add/Remove)."
echo "Type the numbers separated by space (e.g., '1 2 4')."
echo "Type 'all' to select all."
echo "Type 'reset' to clear all active services."
echo ""

# Display Options with Status
for i in "${!SERVICES[@]}"; do
    STATUS="[ ]"
    for a in "${ACTIVE_SERVICES[@]}"; do
        if [[ "$a" == "${SERVICES[$i]}" ]]; then
            STATUS="[X]"
            break
        fi
    done
    echo "$((i+1)). $STATUS ${SERVICES[$i]}"
done
echo "99. Select All"
echo "0. Cancel & Build"

echo ""
read -p "Your choice: " choices

if [[ "$choices" == "0" || -z "$choices" ]]; then
    echo "Processing current selection..."
elif [[ "$choices" == "reset" ]]; then
    echo "Resetting active services..."
    ACTIVE_SERVICES=()
    rm -f "$ACTIVE_FILE" "$TARGET_FILE" "$ENV_FILE"
    echo "Reset complete. Run 'make docker-build' to start over."
    exit 0
elif [[ "$choices" == "all" || "$choices" == "99" ]]; then
    ACTIVE_SERVICES=("${SERVICES[@]}")
else
    # Toggle logic: Add if missing, Remove if exists
    for choice in $choices; do
        if [[ "$choice" -ge 1 && "$choice" -le ${#SERVICES[@]} ]]; then
            idx=$((choice-1))
            srv="${SERVICES[$idx]}"
            
            # Check if exists
            found=0
            new_active=()
            for a in "${ACTIVE_SERVICES[@]}"; do
                if [[ "$a" == "$srv" ]]; then
                    found=1 # Mark for removal
                else
                    new_active+=("$a")
                fi
            done
            
            if [ $found -eq 1 ]; then
                ACTIVE_SERVICES=("${new_active[@]}")
                echo "- Removed $srv"
            else
                ACTIVE_SERVICES+=("$srv")
                echo "+ Added $srv"
            fi
        fi
    done
fi

if [ ${#ACTIVE_SERVICES[@]} -eq 0 ]; then
    echo "No active services. Cleaning up files..."
    rm -f "$ACTIVE_FILE" "$TARGET_FILE"
    exit 0
fi

# Save state
printf "%s\n" "${ACTIVE_SERVICES[@]}" > "$ACTIVE_FILE"

echo ""
echo "Building $TARGET_FILE and updating $ENV_FILE for: ${ACTIVE_SERVICES[*]}..."

# Start with the base template
cp "$BASE_FILE" "$TARGET_FILE"

# Create when first building .env
if [ ! -f "$ENV_FILE" ]; then
    echo "# Auto-generated by make docker-build" > "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

# Ensure services key exists in TARGET_FILE
if ! grep -q "^services:" "$TARGET_FILE"; then
    echo -e "\nservices:" >> "$TARGET_FILE"
fi

# Append selected services
for srv in "${ACTIVE_SERVICES[@]}"; do
    FILE="$DEPLOY_DIR/$srv/service.yml"
    ENV_TPL="$DEPLOY_DIR/$srv/.env.example"
    
    if [ -f "$FILE" ]; then
        sed '1d' "$FILE" >> "$TARGET_FILE"
        echo "" >> "$TARGET_FILE"
        
        if [ -f "$ENV_TPL" ]; then
            while IFS= read -r line || [ -n "$line" ]; do
                if [[ -z "$line" || "$line" == \#* ]]; then
                    continue
                fi
                
                KEY="${line%%=*}"
                if ! grep -q "^$KEY=" "$ENV_FILE"; then
                    echo "$line" >> "$ENV_FILE"
                fi
            done < "$ENV_TPL"
        fi
    else
        echo "Warning: $FILE not found."
    fi
done

# Append Network and Volumes configuration at the very bottom
if [ -f "$NETWORK_FILE" ]; then
    cat "$NETWORK_FILE" >> "$TARGET_FILE"
else
    echo "Warning: $NETWORK_FILE not found."
fi
