#!/bin/bash

# Configuration
BASE_FILE="deployment/00_base.yml"
NETWORK_FILE="deployment/99_base.yml"
TARGET_FILE="docker-compose.yml"
ENV_FILE=".env"
DEPLOY_DIR="deployment"
ACTIVE_FILE=".active_services"

echo "============================================="
echo "   Docker Compose Builder Tool"
echo "============================================="
echo ""

# List of available services map
SERVICES=(
    "nginx-proxy"
    "portainer"
    "adminer"
    "mysql"
    "postgres"
    "redis"
    "iot"
    "minio"
)

# Load existing active services if any
ACTIVE_SERVICES=()
if [ -f "$ACTIVE_FILE" ]; then
    readarray -t ACTIVE_SERVICES < "$ACTIVE_FILE"
fi

if [ ${#ACTIVE_SERVICES[@]} -gt 0 ]; then
    echo "Currently active services: ${ACTIVE_SERVICES[*]}"
    echo ""
fi

echo "Select the services you want to add/include."
echo "Type the numbers separated by space (e.g., '1 2 4')."
echo "Type 'all' for all services."
echo "Type 'reset' to clear previous selections and start over."
echo ""

# Display Options
for i in "${!SERVICES[@]}"; do
    echo "$((i+1)). ${SERVICES[$i]}"
done
echo "99. all"
echo "0. Cancel"

read -p "Your choice: " choices

if [[ "$choices" == "0" ]]; then
    echo "Cancelled."
    exit 0
fi

if [[ "$choices" == "reset" ]]; then
    echo "Resetting active services..."
    ACTIVE_SERVICES=()
    rm -f "$ACTIVE_FILE" "$TARGET_FILE" "$ENV_FILE"
    echo "Please run 'make build' again to select new services."
    exit 0
fi

SELECTED_SERVICES=()

if [[ "$choices" == "all" || "$choices" == "99" ]]; then
    SELECTED_SERVICES=("${SERVICES[@]}")
else
    for choice in $choices; do
        if [[ "$choice" -ge 1 && "$choice" -le ${#SERVICES[@]} ]]; then
            idx=$((choice-1))
            SELECTED_SERVICES+=("${SERVICES[$idx]}")
        fi
    done
fi

# Merge newly selected with active, and unique them
for s in "${SELECTED_SERVICES[@]}"; do
    found=0
    for a in "${ACTIVE_SERVICES[@]}"; do
        if [[ "$a" == "$s" ]]; then
            found=1
            break
        fi
    done
    if [ $found -eq 0 ]; then
        ACTIVE_SERVICES+=("$s")
    fi
done

if [ ${#ACTIVE_SERVICES[@]} -eq 0 ]; then
    echo "No valid services selected."
    exit 1
fi

# Save state
printf "%s\n" "${ACTIVE_SERVICES[@]}" > "$ACTIVE_FILE"

echo "Building $TARGET_FILE and $ENV_FILE for: ${ACTIVE_SERVICES[*]}..."

# Start with the base template
cp "$BASE_FILE" "$TARGET_FILE"

# Start a fresh .env file
echo "# Generated by make build" > "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Ensure services key exists in TARGET_FILE
if ! grep -q "^services:" "$TARGET_FILE"; then
    echo -e "\nservices:" >> "$TARGET_FILE"
fi

for srv in "${ACTIVE_SERVICES[@]}"; do
    FILE="$DEPLOY_DIR/$srv/service.yml"
    ENV_TPL="$DEPLOY_DIR/$srv/.env.example"
    
    if [ -f "$FILE" ]; then
        echo "Appending $srv configuration..."
        sed '1d' "$FILE" >> "$TARGET_FILE"
        echo "" >> "$TARGET_FILE"
        
        # Merge .env
        if [ -f "$ENV_TPL" ]; then
            cat "$ENV_TPL" >> "$ENV_FILE"
            echo "" >> "$ENV_FILE"
        fi
    else
        echo "Warning: $FILE not found."
    fi
done

# Append Network configuration at the very bottom
if [ -f "$NETWORK_FILE" ]; then
    cat "$NETWORK_FILE" >> "$TARGET_FILE"
else
    echo "Warning: $NETWORK_FILE not found."
fi

echo "Done! Generated $TARGET_FILE and $ENV_FILE."
